[package]
name = "rx"
version = "0.0.1"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
license = "Apache-2.0"
readme = "readme.md"
keywords = ["reactive", "observable", "async"]
description = "Reactive programming for Rust"
repository = "https://github.com/ruuda/rx"
