[package]
name = "rx"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
license = "Apache-2.0"
keywords = ["reactive", "observable", "async"]
description = "Reactive programming for Rust"
repository = "https://github.com/ruud-v-a/rx"
